version: '3.9'

x-koha-shared-conf: &koha-shared-conf
  environment:
    - KOHA_INSTANCE_NAME=${KOHA_INSTANCE_NAME}
    - KOHA_INITIAL_ADMIN_NAME=${KOHA_INITIAL_ADMIN_NAME}
    - KOHA_INITIAL_ADMIN_PASS=${KOHA_INITIAL_ADMIN_PASS}
    - KOHA_STAGE_TYPE=${KOHA_STAGE_TYPE}
    - KOHA_OPAC_URL=${KOHA_OPAC_URL}
    - DB_SERVER=${DB_SERVER}
    - DB_PORT=${DB_PORT}
    - DB_ADMIN_USER=${DB_ADMIN_USER}
    - DB_ADMIN_PASS=${DB_ADMIN_PASS}
    - DB_NAME=${DB_NAME}
    - DB_PASS=${DB_PASS}
    - DB_USER=${DB_USER}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

services:
  koha:
    <<: *koha-shared-conf
    # platform: linux/amd64
    container_name: koha
    image: koha:latest
    hostname: koha
    build:
      context: .
      args:
        - KOHA_DEB_REPOSITORY=${KOHA_DEB_REPOSITORY}
    tty: true
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    ports:
      - "80:80"
      - "210:210"
      - "8080:8080"
    depends_on:
      - koha-db

    restart: always

  koha-db:
    <<: *koha-shared-conf
    container_name: koha-db
    image: koha-db:latest
    hostname: mariadb
    build: mariadb
    ports:
      - "3303:3306"
    restart: always

  # koha-zebra:
  koha-memcached:
    container_name: koha-memcached
    image: koha-memcached:latest
    hostname: koha-memcached
    build: memcached
    tty: true
    ports:
      - "11211:11211"
    restart: always

#  koha-elasticsearch:
#    container_name: koha-elasticsearch
#    image: blacktop/elasticsearch:6.8
#    hostname: koha-elasticsearch
#    tty: true
#    ports: 
#      - "9200:9200"
#      - "9300:9300"
#    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=${DB_SERVER}
      - PMA_USER=${DB_ADMIN_USER}
      - PMA_PASSWORD=${DB_ADMIN_PASS}
    restart: "no"
    profiles:
      - dev

networks:
  default:
    name: koha-network
