FROM debian:bullseye

RUN apt-get update
# RUN apt-get install -y memcached libmemcached-tools

# RUN sed -i "s/-l 127.0.0.1/-l koha/g" /etc/memcached.conf

# CMD /etc/inid.d/memcached start
CMD /bin/sh
