FROM mariadb:latest

COPY --chmod=755 entry.sh /docker-entrypoint-initdb.d
# COPY fix.sh /docker-entrypoint-initdb.d/1.fix.sh
# COPY create.sql /docker-entrypoint-initdb.d/create.sql
# RUN chmod +x /entry.sh
